dist: trusty

language: node_js

node_js:
- 9.11.1

before_install:
- npm install -g truffle codecov

install:
- npm install

cache:
  directories:
  - node_modules

script:
- npm run lint
- npm run test:cov